version: '3'

services:
  bookstore-api:
    build: .
    container_name: bookstore-api
    command: /bin/sh -c "/app/start.sh"
    restart: unless-stopped
    ports:
      - "9000:80"
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./api:/app
      - ./start.sh:/app/start.sh
    networks:
      - database
  bookstore-database:
    container_name: bookstore-database
    restart: unless-stopped
    image: postgres:9.6-alpine
    ports: 
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: teste123
      POSTGRES_USER: root
      POSTGRES_DB: bookstore
    logging:
      driver: none
    networks:
      - database

networks:
  database:
    driver: bridge